[project] 
name = "dakota_wheel"
version = "0.0.2"
description = "Dakota wheel"
dependencies = []

[build-system]
requires = ["py-build-cmake", "numpy"]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.sdist]
include = ["dakota/*", "CMakeLists.txt"]

[tool.py-build-cmake.cmake]
source_path = "."
options = {"DAKOTA_PYTHON_WRAPPER" = "ON", "BUILD_SHARED_LIBS"="OFF", "CMAKE_SKIP_INSTALL_RPATH" = "ON", "CMAKE_CXX_FLAGS"="-O3", "CMAKE_CXX_CFLAGS"="-O3", "CMAKE_POSITION_INDEPENDENT_CODE" = "ON"}
build_args = ["-j"]
build_type = "Release"
install_components = ["dakota_for_python"]
