[project] 
name = "itis_dakota"
version = "0.0.3"
description = "Dakota wheel built by the IT'IS Foundation"
dependencies = []

[build-system]
requires = ["py-build-cmake", "numpy"]
build-backend = "py_build_cmake.build"

[tool.cibuildwheel]
before-build = ["pip install numpy", "pip install cmake --upgrade"]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

[tool.py-build-cmake.sdist]
include = ["dakota/*", "CMakeLists.txt", "LICENSE.txt"]

[tool.py-build-cmake.cmake]
source_path = "."
options = {"DAKOTA_PYTHON_WRAPPER" = "ON", "BUILD_SHARED_LIBS"="OFF", "CMAKE_SKIP_INSTALL_RPATH" = "ON", "CMAKE_CXX_FLAGS"="-O3", "CMAKE_CXX_CFLAGS"="-O3", "CMAKE_POSITION_INDEPENDENT_CODE" = "ON", "DAKOTA_PYTHON_DIRECT_INTERFACE" = "ON"}
build_args = ["-j"]
build_type = "Release"
install_components = ["dakota_for_python"]
