[project] 
name = "itis_dakota"
version = "0.0.5"
description = "Dakota wheel built by the IT'IS Foundation, Zurich, Switzerland"
license = { file = "LICENSE.txt" }
readme = {file = "README.md", content-type = "text/markdown"}
dependencies = ["numpy"]
requires-python = ">=3.8"

[project.urls]
homepage = "https://github.com/ITISFoundation/itis-dakota"
repository = "https://github.com/ITISFoundation/itis-dakota.git"
issues = "https://github.com/ITISFoundation/itis-dakota/issues"

[build-system]
requires = ["py-build-cmake", "numpy"]
build-backend = "py_build_cmake.build"

[tool.cibuildwheel]
before-build = ["pip install auditwheel --upgrade", "pip install cmake --upgrade"]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel} && ./scripts/fix_wheel.sh {dest_dir}"
build-verbosity = 2

[tool.cibuildwheel.linux]
environment-pass = ["SCCACHE_GHA_ENABLED", "ACTIONS_CACHE_URL", "ACTIONS_RUNTIME_TOKEN"]
before-all = ["yum install -y lapack-devel boost169-devel blas-devel zip unzip ccache wget", "wget https://github.com/mozilla/sccache/releases/download/v0.7.4/sccache-v0.7.4-x86_64-unknown-linux-musl.tar.gz", "tar xzvf sccache-v0.7.4-x86_64-unknown-linux-musl.tar.gz", "cp sccache-v0.7.4-x86_64-unknown-linux-musl/sccache /usr/bin/"]
skip = "*-musllinux_*"

[tool.py-build-cmake.cmake]
source_path = "."
options = {"CMAKE_CXX_COMPILER_LAUNCHER" = "sccache", "DAKOTA_PYTHON_WRAPPER" = "ON", "BUILD_SHARED_LIBS"="OFF", "CMAKE_POSITION_INDEPENDENT_CODE" = "ON", "DAKOTA_PYTHON_DIRECT_INTERFACE" = "ON", "BOOST_LIBRARYDIR" = "/usr/lib64/boost169", "BOOST_INCLUDEDIR" = "/usr/include/boost169"}
build_args = ["-j8"]
build_type = "Release"
install_components = ["dakota_for_python"]
