[project] 
name = "itis_dakota"
description = "Dakota wheel built by the IT'IS Foundation, Zurich, Switzerland"
license = { file = "LICENSE.txt" }
authors = [
    {name="Werner Van Geit"}
]
readme = {file = "README.md", content-type = "text/markdown"}
dependencies = ["numpy"]
requires-python = ">=3.8"
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/ITISFoundation/itis-dakota"
repository = "https://github.com/ITISFoundation/itis-dakota.git"
issues = "https://github.com/ITISFoundation/itis-dakota/issues"

[build-system]
requires = [
    "py-build-cmake",
    "cmake",
    "auditwheel",
    "setuptools",
    "setuptools_scm",
    "numpy",
    "h5py"
]
build-backend = "build_backend.build"
backend-path = "."

[tool.setuptools]
packages = ["itis_dakota"]
package-dir = {"itis_dakota" = "itis_dakota"}

[tool.setuptools_scm]
version_file = "itis_dakota/_version.py"
local_scheme = "no-local-version"

[tool.cibuildwheel]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel} && ./scripts/fix_wheel.sh {dest_dir}"
build-verbosity = 2

[tool.cibuildwheel.environment]
BOOST_LIBRARYDIR = "/usr/lib64/boost169"
BOOST_INCLUDEDIR = "/usr/include/boost169"

[tool.cibuildwheel.linux]
environment-pass = [
    "SCCACHE_GHA_ENABLED",
    "ACTIONS_CACHE_URL",
    "ACTIONS_RUNTIME_TOKEN"
]
before-all = [
    "yum install -y epel-release yum-utils",
    "yum-config-manager --enable epel",
    "yum makecache --refresh",
    "yum install -y lapack-devel boost169-devel blas-devel hdf5-devel zip unzip ccache wget",
    "wget --progress=dot:mega https://github.com/mozilla/sccache/releases/download/v0.8.1/sccache-v0.8.1-x86_64-unknown-linux-musl.tar.gz",
    "tar xzvf sccache-v0.8.1-x86_64-unknown-linux-musl.tar.gz",
    "cp sccache-v0.8.1-x86_64-unknown-linux-musl/sccache /usr/bin/",
    "pip install setuptools_scm",
    "python -m setuptools_scm --force-write-version-files"
]
skip = "*-musllinux_*"
manylinux-x86_64-image="manylinux_2_28"

[tool.py-build-cmake.cmake]
source_path = "."
build_args = ["-j8"]
build_type = "Release"
install_components = ["dakota_for_python"]

[tool.py-build-cmake.cmake.options]
CMAKE_CXX_COMPILER_LAUNCHER = "sccache"
DAKOTA_HAVE_HDF5 = "ON"
DAKOTA_PYTHON_WRAPPER = "ON"
DAKOTA_PYTHON_DIRECT_INTERFACE = "ON"
BUILD_SHARED_LIBS = "OFF"
CMAKE_POSITION_INDEPENDENT_CODE = "ON"

[tool.pytest.ini_options]
addopts = "--ignore=dakota/"   
