[project] 
name = "itis_dakota"
version = "0.0.3"
description = "Dakota wheel built by the IT'IS Foundation, Zurich, Switzerland"
dependencies = []

[build-system]
requires = ["py-build-cmake", "numpy"]
build-backend = "py_build_cmake.build"

[tool.cibuildwheel]
before-build = ["pip install auditwheel --upgrade", "pip install numpy", "pip install cmake --upgrade"]
#before-build = ["pip install auditwheel --upgrade", "pushd /opt/_internal && tar -xJf static-libs-for-embedding-only.tar.xz && popd", "pip install numpy", "pip install cmake --upgrade"]
before-all = ["yum install -y lapack-static boost169-static blas-static python3-devel.x86_64"]

repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel} && ./scripts/fix_wheel.sh {dest_dir}"
build-verbosity = 2
skip = "*-musllinux_*"

# [tool.py-build-cmake.sdist]
# include = ["dakota/*", "CMakeLists.txt", "LICENSE.txt"]

[tool.py-build-cmake.cmake]
source_path = "."
#options = {"Boost_USE_STATIC_LIBS" = "ON", "DAKOTA_PYTHON_WRAPPER" = "ON", "CMAKE_POSITION_INDEPENDENT_CODE" = "ON", "BUILD_SHARED_LIBS"="OFF", "DAKOTA_PYTHON_DIRECT_INTERFACE" = "ON", "BOOST_LIBRARYDIR" = "/usr/lib64/boost169", "BOOST_INCLUDEDIR" = "/usr/include/boost169", "PYTHON_EXECUTABLE" = "/opt/python/cp38-cp38/bin/python", "PYTHON_INCLUDE_DIR" = "/opt/python/cp38-cp38/include", "PYTHON_LIBRARY" = "/opt/python/cp38-cp38/lib/libpython3.8.a", "PYTHON_LIBRARIES" = "/opt/python/cp38-cp38/lib/"}
options = {"DAKOTA_PYTHON_WRAPPER" = "ON", "CMAKE_POSITION_INDEPENDENT_CODE" = "ON", "BUILD_SHARED_LIBS"="OFF", "DAKOTA_PYTHON_DIRECT_INTERFACE" = "ON", "BOOST_LIBRARYDIR" = "/usr/lib64/boost169", "BOOST_INCLUDEDIR" = "/usr/include/boost169", "PYTHON_EXECUTABLE" = "/opt/python/cp38-cp38/bin/python"}
build_args = ["-j4"]
build_type = "Release"
install_components = ["dakota_for_python"]
