name: build-wheel

on:
    push:
       

jobs:
    wheels:
        name: Building wheel on ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04]
                python: [cp38]
                arch: [x86_64]

        env:
            CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Get dakota src
              run: make get-dakota-src
            - name: Install cibuildwheel
              run: pip install cibuildwheel

