name: build-wheel

on:
    push:
       
jobs:
    wheels:
        name: Building wheel on ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04]
                python: [cp38,cp39,cp310,cp311]
                arch: [x86_64]
        env:
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up sccache
                  uses: mozilla-actions/sccache-action@v0.0.3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Get dakota src
              run: make get-dakota-src
            - uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
                path: ./wheelhouse/*.whl
    test-pypi:
        name: Publish wheels on Test PyPI
        runs-on: ubuntu-latest
        needs:
            - wheels
        environment:
            name: testpypi
            url: https://test.pypi.org/p/itis-dakota
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
                  skip-existing: true
    
    pypi:
        name: Publish wheels on PyPI
        runs-on: ubuntu-latest
        needs:
            - wheels
            - test-pypi
        if: github.ref == 'refs/heads/master'
        environment:
            name: pypi
            url: https://pypi.org/p/itis-dakota
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v3
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              skip-existing: true
