name: build-wheel

on:
    push:
       

jobs:
    wheels:
        name: Building wheel on ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04]
                python: [cp38]
                arch: [x86_64]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Get dakota src
              run: make get-dakota-src
            - uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
                CIBW_BEFORE_ALL: "yum install -y gfortran liblapack-dev libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libblas-dev python3-dev python3-numpy" 
            - name: Upload wheels
              uses: actions/upload-artifact@v3
              with:
                path: wheelhouse/*.whl
