name: build-wheel

on:
    push:
       

jobs:
    wheels:
        name: Building wheel on ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04]
                python: [cp38,cp39,cp310]
                arch: [x86_64]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Get dakota src
              run: make get-dakota-src
            - uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
                #CIBW_BEFORE_ALL: "yum install -y gcc-gfortran lapack-devel boost169-devel boost169-filesystem boost169-program-options boost169-regex boost169-serialization blas-devel"
            - name: Upload wheels
              uses: actions/upload-artifact@v3
              with:
                name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
                path: wheelhouse/*.whl
