name: build-wheel

on:
    push:
       

jobs:
    wheels:
        name: Building wheel on ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04]
                python: [cp38,cp39,cp310]
                arch: [x86_64]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Get dakota src
              run: make get-dakota-src
            - uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
            - name: Upload wheels
              uses: actions/upload-artifact@v3
              with:
                name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
                path: wheelhouse/*.whl
    
    pypi:
        name: Publish wheels on PyPI
        runs-on: ubuntu-latest
        needs: [wheels]
        if: github.ref == 'refs/heads/master'
        environment:
            name: pypi
            url: https://pypi.org/p/itis-dakota
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Download all artifacts
              uses: actions/download-artifact@v3
              with:
                  path: artifacts
            - name: Put artifacts into dist directory
              run: |
                  mkdir -p dist
                  find artifacts -type f \( -iname \*.whl -o -iname \*.tar.gz \) -exec mv {} dist \;
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
